version: 0.0
os: linux
files:
  - source: /webappfiles
    destination: /var/www/html/
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: scripts/pre-install
      timeout: 300
      runas: root
    - location: scripts/start
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop
      timeout: 300
      runas: root
